### PR TITLE
add link to mt7601u

### PR DESCRIPTION
**Pull request by kuba-moo**
Hello!

I would like to add a link to a new Linux driver for mt7601u which was written based on existing Linux Wi-Fi infrastructure and (hopefully) will become part of Linux 3.21. I hope it's OK.

### CODE REVIEW

**Comment by porjo** [comment]
Hello, I took a look at your repo and it looks very promising. It will be great to have a driver in the kernel tree!

Before I update the README can you make some changes:
- link to the specific repository where the code is (e.g. github.com/kuba-moo/mt7601u)
- create a `README` file in your repo with usage instructions, including the kernel version requirement

Thanks!

**Comment by kuba-moo** [comment]
Thanks for the comments. Indeed I somehow managed to miss-paste the link to my repo, good that you caught that! 

I also put a README file in my repo as requested. I guess it contains all necessary information, but don't hesitate to let me know what you think about it.

**Comment by porjo** [comment]
ok, done! I noticed in your README you link to Mediatek website twice in the last paragraph - was that intended?

**Comment by kuba-moo** [comment]
Doh! I guess I've some problems pasting links to the GH online editor... Corrected now, thanks.

**Pull request merged**
